const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_ERROR = 'FETCH_ERROR';

export const FETCH_FAILED = 'FETCH_FAILED';
export const SHOW_LOADER = 'SHOW_LOADER';
export const CURRENT_API = 'CURRENT_API';


//  FETCH_LISTING
const  FETCH_LISTING = 'FETCH_LISTING';
export const  FETCH_LISTING_FETCH =  FETCH_LISTING;
export const  FETCH_LISTING_FETCH_SUCCESS =  FETCH_LISTING + FETCH_SUCCESS;
export const  FETCH_LISTING_FETCH_ERROR =  FETCH_LISTING + FETCH_ERROR;
